# SPDX-FileCopyrightText: 2024 KUNBUS GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later

include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/reuse-lint.yml"

lint-clippy:
  image: rust:latest
  stage: lint
  tags:
    - self-hosted
    - host-arm64
  script:
    - rustup component add clippy
    - cargo clippy --all-features
