# SPDX-FileCopyrightText: 2022-2025 KUNBUS GmbH <support@kunbus.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

[workspace]
members = ["revpi-hat-eep", "rpi-hat-eep"]

[profile.release]
strip = true
